# Generated by Django 4.0.3 on 2022-03-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_remove_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='caionagy', max_length=255),
        ),
    ]
